### ISSUE TITLE
IMPL

### ISSUE THREAD

**Issue by g4s8** [g4s8/CryptoCactoos#1]

**Comment by 0pdd** [comment]
@g4s8 5 puzzles [#3](https://github.com/g4s8/CryptoCactoos/issues/3), [#4](https://github.com/g4s8/CryptoCactoos/issues/4), [#5](https://github.com/g4s8/CryptoCactoos/issues/5), [#6](https://github.com/g4s8/CryptoCactoos/issues/6), [#7](https://github.com/g4s8/CryptoCactoos/issues/7) are still not solved.

**Comment by 0pdd** [comment]
@g4s8 5 puzzles [#10](https://github.com/g4s8/cactoos-crypto/issues/10), [#11](https://github.com/g4s8/cactoos-crypto/issues/11), [#12](https://github.com/g4s8/cactoos-crypto/issues/12), [#13](https://github.com/g4s8/cactoos-crypto/issues/13), [#9](https://github.com/g4s8/cactoos-crypto/issues/9) are still not solved.
